import React from "react";
import { makeStyles } from "@material-ui/core/styles";
import Navbar from "./navBar";
import Footer from "./footer";

const styles = makeStyles((theme) => ({
  term: {
    margin: "100px",
    marginTop: "200px",
    textAlign: "center",
  },
}));
const TermandCond = () => {
  console.log("Teram page  line 11");
  const classes = styles();
  // const theme = useTheme();
  // const isMatch = useMediaQuery(theme.breakpoints.down("sm"));
  return (
    <>
    <Navbar/>
      <h1 className={classes.term}>
        Terms And Contitions This document is an electronic record in terms of
        Information Technology Act, 2000 and rules there under as applicable and
        the amended provisions pertaining to electronic records in various
        statutes as amended by the Information Technology Act, 2000. This
        electronic record is generated by a computer system and does not require
        any physical or digital signatures This document published in accordance
        with the provisions of Rule 3 (1) of the Information Technology
        (Intermediaries guidelines) Rules, 2011 that require publishing the
        rules and regulations, privacy policy and Terms of Use for access or
        usage of domain name [m. Kirana Hub.com/MyKirana] ( Website. ),
        including the related mobile site and mobile application (hereinafter
        referred to as Platform Your use of the Platform and all features
        provided in it are governed by the terms and conditions mentioned on the
        website Terms & Conditions.). By accessing or using the Site, you agree
        to be bound by these Terms. For the purpose of these Terms of Use,
        wherever the context so requires "You' or 'User" shall mean any natural
        or legal person who has agreed to become a buyer on the Platform by
        providing Registration Data while registering on the Platform as
        Registered User using the computer systems, Platform Limitations: KH is
        not a party to the transactions between Buyer and Seller/Retailer on the
        Platform and therefore all commercial Terms and Conditions offered on
        the website are agreed between you and Kirana Hub Ltd/Retailer KH does
        not have control over Policies and commercial terms pertaining to price,
        shipping costs, payment methods, payment terms, date, period and mode of
        delivery, warranties related to products and after sales services
        related to products. KH does not have any control nor does it determine
        or advise or in any way involve itself in the offering or acceptance of
        such commercial/contractual terms between the Buyers and Retailers. All
        discounts, offers (including exchange offers) are by the Retailer and
        not by KH. KH does not at any point of time during any transaction
        between Buyer and Seller on the platform hold title or any possession of
        the products offered by Seller nor does it at any point gain title to or
        have any rights or claims over the products offered by Seller to Buyer.
        KH is not responsible for any non-performance or breach of any contract
        entered into between you and Retailer/Sellers. KH cannot and does not
        guarantee that the concerned Buyers and/or Sellers will perform any
        transaction concluded on the Platform. KH shall not and is not required
        to mediate or resolve any dispute or disagreement between Buyers and
        Sellers. At no time shall KH hold any right, title or interest over the
        products nor shall KH have any obligations or liabilities in respect of
        such contract entered into between Buyers and Sellers. KH is not
        responsible for unsatisfactory or delayed performance of services or
        damages or delays as a result of products which are out of stock,
        unavailable or back ordered. The Platform is only a platform that can be
        utilized by Users to reach a larger base to buy and sell products or
        services. KH is only providing a platform for communication and it is
        agreed that the contract for sale of any of the products or services
        shall be a strictly bipartite contract between the Seller and the Buyer
        YOUR PROFILE & SECURITY: Shoppers have to register and login for placing
        Orders on the Site. As part of the registration process on the Site, you
        maybe required to share information important for us to service you
        efficiently. KH 1. Name including first and last name, 2. mobile phone
        number and 3. postal code, address and information about the pages on
        the site you visit/access, the links you click on the site, the number
        of times you access the page and any such browsing information.
      </h1>
      <Footer/>
    </>
  );
};

export default TermandCond;
